name: markdown_editor_plus
description: A TextField Widget that allow you to convert easily what's in the
  TextField to Markdown with custom toolbar support.

version: 0.3.0
homepage: https://github.com/OmkarDabade/markdown_editor_plus
repository: https://github.com/OmkarDabade/markdown_editor_plus

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  expandable: ^5.0.1
  markdown: ^7.1.0
  flutter_markdown: ^0.6.15
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: null
